### ISSUE TITLE
Cassette depency warning

### ISSUE THREAD

**Issue by freemin7** [JuliaDiffEq/SparseDiffTools.jl#56]
Hello,

i am running Julia 1.0.4 just updated some packages which now require SparseDiffTools.
I just wanted to let you know that warning:

┌ Warning: Package SparseDiffTools does not have Cassette in its dependencies:
│ - If you have SparseDiffTools checked out for development and have
│   added Cassette as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with SparseDiffTools
└ Loading Cassette into SparseDiffTools from project dependency, future warnings for SparseDiffTools are suppressed.

**Comment by devmotion** [comment]
Hej!

Unfortunately, this problem occurs currently if you use both SparseDiffTools and Cassette. It was not captured by our tests of SparseDiffTools and Cassette, I guess, since Cassette is a test dependency of SparseDiffTools.

The current problem in the SparseDiffTools implementations are all calls and overrides of the form `Cassette.`. Instead we should use `using .Cassette: ...` and `import .Cassette: ...` and remove `Cassette.` from these calls. Unfortunately, that's not sufficient since the macros `@context` and `@pass`  in Cassette add explicit calls of the form `Cassette.` - by just crudely replacing those macros with a version without `Cassette.` and `using .Cassette: ...` all required methods I'm able to get rid of the warning, but it completely breaks SparseDiffTools :disappointed: It might very well be the case that there are some bugs in my implementation, but maybe that cleanest solution would just be to move the automatic sparsity detection to a separate package.

**Comment by ChrisRackauckas** [comment]
Split out to a separate package.

@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
